# Generated by Django 3.0.6 on 2020-08-05 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=10, unique=True)),
                ('enquiry_id', models.CharField(max_length=50)),
                ('course_fee', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2020, 8, 5))),
                ('notes', models.TextField(null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_date', models.DateField(default=datetime.date(2020, 8, 5))),
                ('batch_status', models.CharField(choices=[('1', 'Yet to begin'), ('2', 'Ongoing'), ('3', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_name', models.CharField(max_length=50)),
                ('counsellor_phone', models.IntegerField(null=True)),
                ('counsellor_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enquiry_date', models.DateField(default=datetime.date(2020, 8, 5))),
                ('followup_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Call_Back'), ('2', 'Admitted'), ('3', 'Cancel')], max_length=20)),
                ('batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Batch')),
                ('counsellor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Counsellor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField(default=datetime.date(2020, 8, 5))),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Admission')),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Enquiry')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Course'),
        ),
        migrations.AddField(
            model_name='admission',
            name='batch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Batch'),
        ),
    ]
