# Generated by Django 3.0.6 on 2020-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20200819_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_no',
            field=models.CharField(editable='False', max_length=30),
        ),
    ]
