# Generated by Django 3.0.6 on 2020-08-26 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20200819_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 26)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2020, 8, 26)),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_email',
            field=models.EmailField(blank='True', max_length=254, null='True'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_phone',
            field=models.IntegerField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 8, 26)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2020, 8, 26)),
        ),
    ]
