# Generated by Django 3.0.6 on 2020-09-09 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20200826_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_phone',
            field=models.CharField(blank='True', max_length=13, null='True'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2020, 9, 9)),
        ),
    ]
