# Generated by Django 3.0.6 on 2020-09-22 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_auto_20200909_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='notes',
            field=models.TextField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 22)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2020, 9, 22)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2020, 9, 22)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2020, 9, 22)),
        ),
    ]
